title: Churchill Archives Centre digital archives documentation

logo: "/assets/ChurchillArchivesCentre-logo-white-RGB.png"
favicon_ico: "/assets/favicon.png"

remote_theme: just-the-docs/just-the-docs
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true
color_scheme: "dark"

ga_tracking: G-BKFCY4YMVP
ga_tracking_anonymize_ip: true
