#title: Churchill Archives Centre digital archives documentation
#email: archives@chu.cam.ac.uk
#description: >- 
# Documentation for ingest and manipulation of born digital and digitised archival material at Churchill Archives Centre, UK.
#baseurl: "" # the subpath of your site, e.g. /blog

remote-theme: just-the-docs/just-the-docs
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true
color_scheme: "dark"

ga_tracking: G-BKFCY4YMVP
ga_tracking_anonymize_ip: true
